services:
  frontend:
    build:
      context: .
    ports:
      - 9876:80
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - backend
  backend:
    build:
      context: .
    environment:
      - DATABASE_DB=${DB_NAME}
      - DATABASE_USER=${DB_USER}
      - DATABASE_PASSWORD=${DB_PASSWORD}
      - DATABASE_HOST=db
      - SERVER_HOST=backend
      - SERVER_PORT=8766
    ports:
      - ${SERVER_PORT}:${SERVER_PORT}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - db
  db:
    image: postgres
    restart: always
    user: postgres
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    ports:
      - ${DB_PORT}:${DB_PORT}
    expose:
      - 5432
    healthcheck:
      test: ["CMD", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5
volumes:
  db-data:
