name: Build and Push to GHCR

on:
  push:
    branches: ["main"]

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    permissions:
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to ghcr.io registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push Backend image to GHCR
        run: |
          docker build --target backend -t ghcr.io/ewbidev/typey-backend:latest .
          docker push ghcr.io/ewbidev/typey-backend:latest

      - name: Build and Push Frontend image to GHCR
        run: |
          docker build --target frontend -t ghcr.io/ewbidev/typey-frontend:latest .
          docker push ghcr.io/ewbidev/typey-frontend:latestÏ
